"""Add PlanUpgradeRequest

Revision ID: b3e7f0b435e2
Revises: f08ae9d4f395
Create Date: 2026-06-08 07:56:03.779941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e7f0b435e2'
down_revision: Union[str, None] = 'f08ae9d4f395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_upgrade_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='upgraderequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upgrade_request_status', 'plan_upgrade_requests', ['status'], unique=False)
    op.create_index(op.f('ix_plan_upgrade_requests_status'), 'plan_upgrade_requests', ['status'], unique=False)
    op.create_index(op.f('ix_plan_upgrade_requests_user_id'), 'plan_upgrade_requests', ['user_id'], unique=False)
    op.alter_column('chats', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_user_month', 'token_usage', type_='unique')
    op.drop_index('idx_token_usage_user_month', table_name='token_usage')
    op.create_index('idx_token_usage_user_month', 'token_usage', ['user_id', 'month'], unique=True)
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_index('idx_token_usage_user_month', table_name='token_usage')
    op.create_index('idx_token_usage_user_month', 'token_usage', ['user_id', 'month'], unique=False)
    op.create_unique_constraint('uq_user_month', 'token_usage', ['user_id', 'month'])
    op.alter_column('chats', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_plan_upgrade_requests_user_id'), table_name='plan_upgrade_requests')
    op.drop_index(op.f('ix_plan_upgrade_requests_status'), table_name='plan_upgrade_requests')
    op.drop_index('idx_upgrade_request_status', table_name='plan_upgrade_requests')
    op.drop_table('plan_upgrade_requests')
    # ### end Alembic commands ###
