"""Initial baseline

Revision ID: f08ae9d4f395
Revises: 
Create Date: 2026-05-23 19:55:36.431379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f08ae9d4f395'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('focus_area', sa.String(length=100), nullable=True),
    sa.Column('filing_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('idx_status_created', 'analysis_tasks', ['status', 'created_at'], unique=False)
    op.create_index('idx_ticker_year', 'analysis_tasks', ['ticker_symbol', 'filing_year'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_ticker_symbol'), 'analysis_tasks', ['ticker_symbol'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_user_id'), 'analysis_tasks', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.Enum('HYBRID', 'PRIVATE', name='chatmode'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_chats', 'chats', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('is_system_doc', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processing_status', 'documents', ['processing_status'], unique=False)
    op.create_index('idx_user_docs', 'documents', ['user_id', 'is_system_doc'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_user_month', 'token_usage', ['user_id', 'month'], unique=True)
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('idx_chat_messages', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_index('idx_token_usage_user_month', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index('idx_user_docs', table_name='documents')
    op.drop_index('idx_processing_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index('idx_user_chats', table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_analysis_tasks_user_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_ticker_symbol'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_index('idx_ticker_year', table_name='analysis_tasks')
    op.drop_index('idx_status_created', table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Drop PostgreSQL ENUM types that survive table drops
    op.execute("DROP TYPE IF EXISTS messagerole")
    op.execute("DROP TYPE IF EXISTS chatmode")
    op.execute("DROP TYPE IF EXISTS processingstatus")
    op.execute("DROP TYPE IF EXISTS taskstatus")
    # ### end Alembic commands ###


